name: Hardcore
api: 5.0.0
main: Biswajit\Heardcore\Main
version: 1.0.0
author: Biswajit
description: "A Hardcore Plugin Ban Player On Death"
softdepend: ["BedrockEconomy", "EconomyAPI"]

commands:
    revive:
        description: "Use To Revive A Ban Player"
        permission: Hardcore.cmd.revive

permissions:
    Hardcore.cmd.revive:
        description: "Permission To Use /revive Command"
        default: true
